# Generated by Django 4.2.6 on 2023-10-14 09:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('duracion', models.FloatField()),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('correo_electronico', models.TextField(unique=True)),
                ('contraseña', models.TextField()),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('prioridad', models.IntegerField()),
                ('estadio', models.CharField(choices=[('PE', 'Pendiente')], default='PE', max_length=2)),
                ('completada', models.BooleanField()),
                ('fechaCreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('horaVencimineto', models.DateField()),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebaModelos.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos_asignados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebaModelos.proyecto')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebaModelos.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='creador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pruebaModelos.usuarios'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tareas_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebaModelos.tarea'),
        ),
        migrations.CreateModel(
            name='Etiquetas_asociadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebaModelos.etiqueta')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebaModelos.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=100)),
                ('fechaComentario', models.DateTimeField()),
                ('autor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pruebaModelos.usuarios')),
                ('rel_tarea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pruebaModelos.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oberservaciones', models.CharField(max_length=100)),
                ('fechaAsignacion', models.DateTimeField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebaModelos.usuarios')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebaModelos.tarea')),
            ],
        ),
    ]
